site_name: EduChatEval
site_url: https://github.com/laurawpaaby/EduChatEval
repo_url: https://github.com/laurawpaaby/EduChatEval
docs_dir: 'docs/'


theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  font:
    text: Roboto Serif
  logo: 'pics/logo.png'
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: pink
      accent: pink  
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep purple
      accent: indigo

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
    - Overview: user_guides/userguide_intro.md
    - Guides: user_guides/guide.md
    - Templates: user_guides/frameworks.md
  - API: 
    - Framework Generation: api/api_frame_gen.md
    - Synthesizing Interactions: api/api_synth_int.md
    - Wrap Interactions: api/api_wrap_int.md
    - Predict Labels: api/api_pred.md
    - Visualizations: api/api_viz.md
  - About: about.md


plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
            docstring_style: google
            show_init: false
            members_order: source
        
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/laurawpaaby/EduChatEval/tree/main 
    
copyright: Copyright &copy; 2025 Laura Wulff Paaby